# Generated by Django 5.0.14 on 2026-10-02 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('article', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Артикул')),
                ('amount_amd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена, AMD')),
                ('amount_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена, RUB')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена, USD')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('supplier', models.TextField(blank=True, verbose_name='Поставщик')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Позиция каталога',
                'verbose_name_plural': 'Каталог',
                'ordering': ['-updated_at'],
            },
        ),
    ]
