# Generated by Django 5.0.14 on 2026-10-02 06:06

from django.db import migrations, models


def copy_facebook_text_into_meta_text(apps, schema_editor):
    """facebook_text and instagram_text are merging into one meta_text field
    (one shared text for both platforms going forward). For existing rows,
    keep the facebook_text version — it's already written in the
    platform-neutral tone meta_text is meant to have.
    """
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.exclude(facebook_text=""):
        post.meta_text = post.facebook_text
        post.save(update_fields=["meta_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_text',
            field=models.TextField(blank=True, help_text='Публикуется без изменений в Facebook и Instagram.', verbose_name='Текст для Facebook/Instagram (Meta)'),
        ),
        migrations.RunPython(copy_facebook_text_into_meta_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='post',
            name='facebook_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram_text',
        ),
        migrations.AddField(
            model_name='post',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Обязательна, если пост попадёт в соц.сети или на list.am/avito.', max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='post',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('AMD', 'AMD (драм)'), ('RUB', 'RUB (рубль)'), ('USD', 'USD (доллар)')], default='AMD', max_length=3, verbose_name='Валюта цены'),
        ),
    ]
